#!/bin/sh
set -e

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include=php:/etc/drupaltestbot/config-checkout.php
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_go drupaltestbot-mysql $@

#DEBHELPER#
