#!/bin/sh
set -e

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

# source dbconfig-common stuff
if [ -f /usr/share/dbconfig-common/dpkg/postrm.sqlite3 ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.sqlite3
	dbc_go drupaltestbot-sqlite3 $@
fi

if [ "$1" = "purge" ]; then
	rm -f /etc/drupaltestbot/config-checkout.php
	if which ucf >/dev/null 2>&1; then
		ucf --debconf-ok --purge /etc/drupaltestbot/config-checkout.php
	fi
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

