#!/bin/sh
set -e

apache_remove() {
	if [ -d /etc/apache2/sites-enabled ] && [ -L /etc/apache2/sites-enabled/drupaltestbot ]; then
		rm -f /etc/apache2/sites-enabled/drupaltestbot
	fi
	reload_apache
}

reload_apache() {
	if apache2ctl configtest 2>/dev/null; then
		invoke-rc.d apache2 force-reload || true
	else
		echo "Your apache2 configuration is broken, so we're not restarting it for you."
	fi
}

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

# source dbconfig-common stuff
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.mysql
	dbc_go drupaltestbot $@
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	apache_remove

	if [ "$1" = "purge" ]; then
		rm -f /etc/drupaltestbot/config-db.php
		if which ucf >/dev/null 2>&1; then
			ucf --debconf-ok --purge /etc/drupaltestbot/config-db.php
		fi
	fi
fi

#DEBHELPER#
