#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.sqlite3 ]; then
        . /usr/share/dbconfig-common/dpkg/config.sqlite3
        dbc_go drupaltestbot-sqlite3 $@
fi
