#!/bin/sh
set -e

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.pgsql
dbc_generate_include=php:/etc/drupaltestbot/config-checkout.php
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_pgsql_createdb_encoding UNICODE
dbc_go drupaltestbot-pgsql $@

#DEBHELPER#
