#!/bin/sh
set -e

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

# source dbconfig-common stuff
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.pgsql
	dbc_go drupaltestbot-pgsql $@
fi

if [ "$1" = "purge" ]; then
	rm -f /etc/drupaltestbot/config-checkout.php
	if which ucf >/dev/null 2>&1; then
		ucf --debconf-ok --purge /etc/drupaltestbot/config-checkout.php
	fi
fi

#DEBHELPER#
