#!/bin/sh
set -e

apache_install() {
	rm /etc/apache2/sites-enabled/* || true
	ln -s /etc/apache2/sites-available/drupaltestbot /etc/apache2/sites-enabled/drupaltestbot
	reload_apache
}

reload_apache() {
	if apache2ctl configtest 2>/dev/null; then
		invoke-rc.d apache2 force-reload || true
	else
		echo "Your apache2 configuration is broken, so we're not restarting it for you."
	fi
}

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include=php:/etc/drupaltestbot/config-db.php
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_go drupaltestbot $@

if [ "$1" = "configure" ]; then
	apache_install

	# Permissions
	filesdir="/var/lib/drupaltestbot/sites/default/files"
	dpkg-statoverride --list $filesdir || dpkg-statoverride --add --force --update www-data www-data 0750 $filesdir
fi

#DEBHELPER#
